# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FD
email: fd@gmail.com
description: FD
baseurl: “/web5“ # the subpath of your site, e.g. /blog
url: "http://felixdietrich.github.com" # the base hostname & protocol for your site
future: true # allows future dated posts

#social networks
twitter_username: felixdietrich87
github_username: felixdietrich
facebook_username: f.b.dietrich

# Build settings
markdown: kramdown

# Other Options
permalink: blog/:year/:month/:title/
excerpt_separator: "<!--more-->"
